name: "PR: Welcome a first-time contributor"

on:
  pull_request_target:
    types: opened

jobs:
  welcome-first-time-contributor:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: plbstl/first-contribution@v3
        with:
          issue-opened-msg: |
            ### Hey @{fc-author} !

            Looks like it's your first pull reqests to Armbian codebase.

            Welcome and thank you for contributing :heart: :heart: :heart:.

            Don't forget to star :star: the repo.
